version: "2.1"
services:
  box:
    image: "172.29.23.100:5000/marm-spring-box"
    container_name: marm-spring-box
    ports:
      - "28080:8080"
    depends_on:
      - postgres
      - mongo
  postgres:
    image: "172.29.23.100:5000/marm-spring-postgres"
    container_name: marm-spring-postgres
    ports:
      - "25432:5432"
  mongo:
    container_name: marm-spring-mongo
    image: "172.29.23.100:5000/marm-spring-mongo"
    ports:
      - "27018:27017"



# volumes:
#   arbitrary-repo-name:
#     driver_opts:
#       type: none
#       device: /var/log
#       o: bind
#   arbitrary-repo-namee:
#     driver_opts:
#       type: none
#       device: /var/log
#       o: bind